option0="""
asdfasfdasdfasdfasdf
asfasdf
sadfasdfasdf
sadfasfdasdfasdfasd
fasdfasdf
asdfasdf
safasdfasdfsdafsdfasdfasdf
sadfsdfasd
fsdfsadf
sadfasdfasdfsadf
asdfsadfsdfasdf"""[1:0]
option1="""
asdfasfdasdfasdfasdf
asfasdf
sadfasdfasdf
sadfasfdasdfasdfasd
fasdfasdf
asdfasdf
safasdfasdfsdafsdfasdfasdf
sadfsdfasd
fsdfsadf
sadfasdfasdfsadf
asdfsadfsdfasdf"""[1:0]
option2="""
asdfasfdasdfasdfasdf
asfasdf
sadfasdfasdf
sadfasfdasdfasdfasd
fasdfasdf
asdfasdf
safasdfasdfsdafsdfasdfasdf
sadfsdfasd
fsdfsadf
sadfasdfasdfsadf
asdfsadfsdfasdf"""[1:0]
option3="""
asdfasfdasdfasdfasdf
asfasdf
sadfasdfasdf
sadfasfdasdfasdfasd
fasdfasdf
asdfasdf
safasdfasdfsdafsdfasdfasdf
sadfsdfasd
fsdfsadf
sadfasdfasdfsadf
asdfsadfsdfasdf"""[1:0]